### ISSUE TITLE
update required for EF core 3.0

### ISSUE THREAD

**Issue by vvaidyanathan** [verdie-g/StoredProcedureEFCore#24]
hello -

Your StoredProcedureEFCore works very well.  But I had trouble when i updated my project to use EF core 3.0 and dotnet core 3.0.  
Can you please update StoredProcedureEFCore for EF core 3.0 ? mainly the reference to Microsoft.EntityFrameworkCore.Design needs to be updated to the latest version I think.

Thanks!

**Comment by verdie-g** [comment]
Updating Microsoft.EntityFrameworkCore.Design to 3.0.0 would mean updating the library to .NET Standard 2.1. People couldn't reference the nuget from a version lower than .NET Core 3.0.

Currently, the library targets .NET Standard 1.3. It should work fine for you. What kind of trouble are you experiencing ?

I'll upgrade to .NET Standard 2.0 though, as it is advised in [this article](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting).

**Comment by vvaidyanathan** [comment]
I have updated my project to use Dotnet core 3.0 and when i tried to run a migration I got the following error:
*****************start error*****************************
PM> Add-migration AddEmailfieldstoRefundtable
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Internal.LazyRef`1' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
  at Microsoft.EntityFrameworkCore.Design.OperationExecutor..ctor(Object reportHandler, IDictionary args)
  --- End of inner exception stack trace ---
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
  at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
  at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
  at System.Activator.CreateInstance(Type type, Object[] args)
  at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language)
  at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
  at Microsoft.EntityFrameworkCore.Tools.Commands.MigrationsAddCommand.Execute()
  at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
  at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
  at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Exception has been thrown by the target of an invocation.

*********************************end error*********************************

Researching pointed to mixed versions of Microsoft.EntityFrameworkCore.Design.  I had version 3.0 in my project which is required for dotnet core 3.0.  To workaround the issue, i removed StoredProcedureEFCore and ran the migration.  Migration worked.  Then re-installed StoredProcedureEFCore.  This is not an optimum solution for me as i need to run more migrations.

Thanks!

**Comment by verdie-g** [comment]
It seems like it is more an issue with the migration tool. I would advise you to open an issue on their repo. Anyway StoredProcedureEFCore will stick to .NET Standard 2.0.

**Comment by gjunge** [comment]
I know the issue is closed, but wouldn’t it an option to multi target it to both netstandard 2.0 and netstandard 2.1? This way you have your cake and eat it too. If you want I can give it a go and send you a PR.

**Comment by verdie-g** [comment]
What is the benefit of targeting .NET Standard 2.1? An application targeting .NET Core 3.X should be able to target .NET Standard 2.0.

**Comment by gjunge** [comment]
Correct, but this way you can differentiate between EF3 and EF2, since EF3 only targets netstandard 2.1.  

So in that case if we multitarget then netstandard 2.0 references EF2 and netstandard 2.1 references EF 3.

**Comment by verdie-g** [comment]
Maybe I'm missing something, but I don't see the issue. StoredProcedureEFCore has a dependency on Microsoft.EntityFrameworkCore.Design >= 2.2.6, it should work with EF3.

**Comment by gjunge** [comment]
Since from my part this has been purely theoretical, meaning I didn’t run it with EF Core 3.0, I assume you are right.
